trigger:
- main

pool:
  name: selfhostedvm

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install setuptools
        pip install -r requirements.txt
  displayName: "Install requirements"