trigger:
- main

pool: Default

steps:
- script: |
    python3 --version
    python3 -m pip --version

    python3 -m venv antenv
    source antenv/bin/activate

    python -m pip install --upgrade pip
    pip install setuptools
    pip install -r requirements.txt
  displayName: "Install Python dependencies"
